# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=11)),
                ('categoria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='produto.Categoria')),
            ],
        ),
    ]
